export const types = {
    // AUTH ACTIONS
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    // CREATE ACCOUNT ACTIONS
    CREATE_ACCOUNT_START: "CREATE_ACCOUNT_START",
    CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
    CREATE_ACCOUNT_FAILURE: "CREATE_ACCOUNT_FAILURE"
}